Algoritmo "Meu primeiro algoritimo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Santana
// Data atual  : 26/05/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Resultado:", nota)

Fimalgoritmo